### PR TITLE
Update ApplicationChrome.cs

### PR DESCRIPTION
**Pull request by OJ3D**
The script required more detail for the androidobjects and call methods.
a couple vars swapped with AndroidJavaObject and the call methods needed specification such as .Call<AndroidJavaObject>
Also swapped the USE_ANDROID for UNITY_ANDROID
All compiled, built, and worked like a charm in the latest unity 5.2.3

### CODE REVIEW

**Comment by OJ3D** [comment]
Zeh - thanks again for the code, as I saw on another forum that the status bar toggle/supportability was randomly removed in unity. I'm building for android 4.0 (Ice cream) and using jdk1.7.0_75. The error doesn't occur until you create the build. It halted near the start of the build-hence the error statement in the issue feed I provided. Let me know  if you can reproduce the error. The USE_ANDROID makes sense, made these edits late last night

**Comment by zeh** [comment]
Cool, I'm creating a emulator image and taking a look right now. Although if it's a build error it shouldn't be related to OS version... we'll see.

I'm seeing other random people reporting similar errors online in code that (IMO) should work fine, so it _might_ also be something that Unity throws randomly.

**Comment by zeh** [comment]
Hey man, here's an update of sorts.

I can't test the bug on Android 4 using the emulator.. unfortunately the emulator cannot emulate GPU for API < 15, and because GPU cannot be emulated, Unity tests don't run at all... and I don't have a 4.0.x device to test.

It seems to still be working on the emulator with other versions, but again I'm on Unity 5.3.

There's probably SOME combination of the build settings that's making it break.. I haven't been able to replicate it though.

My suggestion is this - replace the `var` calls on those loops with the correct class declaration, test to see if it works. If it does, update the PR with that change (or submit a new one!) and I'll merge it.

**Comment by zeh** [comment]
Hey @OJ3D. Just catching up with this.

`ApplicationChrome` is working fine now with Unity 2019.3. I've done a small update too to fix a separate problem.

Android < 4.4 is becoming a bit irrelevant with 3% worldwide, so I'm not sure if there's anything worth addressing now.

I'm closing this, but let me know if you notice anything else that can still be addressed.

**Pull request closed without merging**
